with open('numar.txt','r') as f:
    a=f.readline()
    b=int(a)*1
    c=int(a)*2
    d=int(a)*3
    e=int(a)*4
    x=int(a)*5
    g=int(a)*6
    h=int(a)*7
    i=int(a)*8
    j=int(a)*9
    k=int(a)*10
with open('inmultire.txt','w') as f:
    f.write('1x')
    f.write(str(a))
    f.write('=')
    f.write(str(b))
    f.write("\n")
    f.write('2x')
    f.write(str(a))
    f.write('=')
    f.write(str(c))
    f.write("\n")
    f.write('3x')
    f.write(str(a))
    f.write('=')
    f.write(str(d))
    f.write("\n")
    f.write('4x')
    f.write(str(a))
    f.write('=')
    f.write(str(e))
    f.write("\n")
    f.write('5x')
    f.write(str(a))
    f.write('=')
    f.write(str(x))
    f.write("\n")
    f.write('6x')
    f.write(str(a))
    f.write('=')
    f.write(str(g))
    f.write("\n")
    f.write('7x')
    f.write(str(a))
    f.write('=')
    f.write(str(h))
    f.write("\n")
    f.write('8x')
    f.write(str(a))
    f.write('=')
    f.write(str(i))
    f.write("\n")
    f.write('9x')
    f.write(str(a))
    f.write('=')
    f.write(str(j))
    f.write("\n")
    f.write('10x')
    f.write(str(a))
    f.write('=')
    f.write(str(k))